language: node_js
jobs:
  include:
  - stage: install
    script: npm install
    skip_cleanup: true
  - stage: test
    before_script:
      - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
      - chmod +x ./cc-test-reporter
      - ./cc-test-reporter before-build
    script: 
      - jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
    after_script:
      - ./cc-test-reporter after-build -t lcov -r $CODE_CLIMATE
      - rm -rf ./coverage

  - stage: release
    deploy:
      provider: script
      skip_cleanup: true
      script:
      - npm run build && npm run copyfiles && cd dist && npx semantic-release
    if: branch = master