language: node_js
jobs:
  include:
  - stage: install
    script: npm install
    skip_cleanup: true
  - stage: test
    script: jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
  - stage: release
    deploy:
      provider: script
      skip_cleanup: true
      script:
      - npm run build && npm run copypackage && cd dist && npx semantic-release
    if: branch = master